### PR TITLE
Tweaks on pr2

### PR DESCRIPTION
**Pull request by itzg**
@GeorgeJahad here's a PR/branch where I'm pushing tweaks against your #2 PR

### CODE REVIEW

**Comment by itzg** [comment]
At first I saw `testRebalanceRounding` fail, made these mostly cosmetic changes, and now I can't see it fail after re-running just that unit test 5+ times in a row. I'm wondering if there's some cross-test noise that is interfering with test repeatability.

**Comment by GeorgeJahad** [comment]
I've run this branch in a loop, like i mentioned in my pr.  like that one it fails about 25% of the time.

here are the errors i've seen so far:
```

gun3006.txt:java.lang.AssertionError: hasActiveWorkItems failed to see in time 3, had 1
gun3006.txt-	at me.itzg.tryetcdworkpart.services.WorkAllocatorTest.testTwoWorkersReleasedToOne(WorkAllocatorTest.java:280)
--
gun3007.txt:java.lang.AssertionError: hasActiveWorkItems failed to see in time 3, had 0
gun3007.txt-	at me.itzg.tryetcdworkpart.services.WorkAllocatorTest.testTwoWorkersReleasedToOne(WorkAllocatorTest.java:280)
--
gun3010.txt:java.lang.AssertionError: hasActiveWorkItems failed to see in time 3, had 0
gun3010.txt-	at me.itzg.tryetcdworkpart.services.WorkAllocatorTest.testTwoWorkersReleasedToOne(WorkAllocatorTest.java:280)
--
gun3012.txt:java.lang.AssertionError: hasActiveWorkItems failed to see in time 2, had 4
gun3012.txt-	at me.itzg.tryetcdworkpart.services.WorkAllocatorTest.testRebalanceRounding(WorkAllocatorTest.java:224)
--
gun3012.txt:java.lang.AssertionError: hasActiveWorkItems failed to see in time 3, had 0
gun3012.txt-	at me.itzg.tryetcdworkpart.services.WorkAllocatorTest.testTwoWorkersReleasedToOne(WorkAllocatorTest.java:281)
--
gun3013.txt:java.lang.AssertionError: hasActiveWorkItems failed to see in time 3, had 0
gun3013.txt-	at me.itzg.tryetcdworkpart.services.WorkAllocatorTest.testTwoWorkersReleasedToOne(WorkAllocatorTest.java:280)
```

**Comment by itzg** [comment]
Thanks. I was about to try looping the test runs myself and the info about which tests tend to fail answers a question a had.

**Comment by itzg** [comment]
@GeorgeJahad I'm not sure if it's the luck of me running it, but with this latest commit I got the 20 in a row to succeed. I made the unit test work allocator stopping more robust by doing it in `tearDown` and leveraging the stop-callback to have the tearDown wait for all to be stopped before concluding the test case.

**Comment by GeorgeJahad** [comment]
that does seem better.  I got two errors in 40 runs:


```
java.lang.AssertionError: hasActiveWorkItems failed to see in time 3, had 5
	at me.itzg.tryetcdworkpart.services.WorkAllocatorTest.testOneWorkerJoinedByAnother(WorkAllocatorTest.java:196)
--
java.lang.AssertionError: hasActiveWorkItems failed to see in time 3, had 5
t-	at me.itzg.tryetcdworkpart.services.WorkAllocatorTest.testOneWorkerJoinedByAnother(WorkAllocatorTest.java:196)
```

**Comment by itzg** [comment]
@GeorgeJahad can you post the logs for one of those if you still have it? I had done 2 runs of 20 and hadn't see failures yet...so nothing to investigate :)

**Comment by itzg** [comment]
Maybe the 1 second timeout is too aggressive for the assertion:

https://github.com/itzg/try-etcd-work-allocator/blob/tweaks-on-pr2/src/test/java/me/itzg/tryetcdworkpart/services/WorkAllocatorTest.java#L196-L197

**Comment by itzg** [comment]
While looking through the code, I'm wondering if releasing the whole batch of work items in one transaction instead of one by one would help anything:

https://github.com/itzg/try-etcd-work-allocator/blob/30d4d3eb933de015e63938a3a70f71bf9d917588/src/main/java/me/itzg/tryetcdworkpart/services/WorkAllocator.java#L371-L382

**Comment by GeorgeJahad** [comment]
here are the two failure runs out of the 40 i ran, with your latest commits:

[gun4007.txt](https://github.com/itzg/try-etcd-work-allocator/files/2637575/gun4007.txt)
[gun4012.txt](https://github.com/itzg/try-etcd-work-allocator/files/2637577/gun4012.txt)

**Comment by GeorgeJahad** [comment]
i ran it forty more times and got 2 errors again, so it definitely seems better.   here are the files:
[gun5001.txt](https://github.com/itzg/try-etcd-work-allocator/files/2637612/gun5001.txt)
[gun5008.txt](https://github.com/itzg/try-etcd-work-allocator/files/2637615/gun5008.txt)

**Comment by itzg** [comment]
Picking one at random, gun5001, the failed test does show a mysterious gap of activity between these two log entries:

https://gist.github.com/itzg/915effa7e134d94abc63ba920d02b2fb#file-part_of_gun5001-txt-L55-L62

Since the original worker saw the new one at 15:54:59.314 it should have initiated the rebalance 500ms later at :59.814, but that seems to be part that's primarily missing from the flow.

I pushed a commit that creates a constant and increases all of those timeouts to 5 seconds.

**Comment by itzg** [comment]
Just as a note, here's a successful observation of the new worker and then the rebalance

https://gist.github.com/itzg/e64670ebaa32d0450188f81febe9dfbc

**Comment by GeorgeJahad** [comment]
impressive.  40 runs without error  that time

**Comment by itzg** [comment]
Excellent. Hopefully that means we’ve converged and not just down to 1 in 60 failures :). Feel free to just merge these commits into your branch or we can go vice versa.

**Review by GeorgeJahad — APPROVED** [review]
Note that I would like to add my clean up pr as well:
https://github.com/itzg/try-etcd-work-allocator/pull/4

**Pull request merged**
